Why numpy over lists?
- Numpy is faster than lists
- Numpy uses fixed types
eg: 5 => binary => numpy => int 32/int 16
5 => binary => lists store as built in int types => stores size, reference count, object type and object value .. requires a lot more space
- No need to type check each time
- numpy uses contiguous memory
- SIMD Vector processing due to contiguous memory
- effective cache utilization

How are lists different from numpy?

In Lists:

a=[1,3,5]

b=[1,2,3]

a*b= ERROR

In NumPy:

a*b=np.array([1,6,15])

In [1]:
import numpy as np

In [3]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b= np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [9]:
# Get dims
print(a.ndim)
print(b.ndim)

1
2


In [8]:
# shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [10]:
# type of np array
print(a.dtype)

int64


In [11]:
# to specify the type
c=np.array([1,2,3], dtype='int16')

In [12]:
# get size
print(a.itemsize)
print(c.itemsize)

8
2


In [15]:
# total size
print(a.size *a.itemsize)
print(a.nbytes)
# no of elements * size

24
24


Accessing/changing specific rows/columns

In [18]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
# get a specific element
print(a[1,5])
print(a[1,-2])

13
13


In [21]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
# get a specific column
a[:,1]

array([2, 9])

In [23]:
# getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [24]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [25]:
a[:,2]=5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [26]:
a[:,2]=60,40
print(a)

[[ 1  2 60  4  5  6  7]
 [ 8  9 40 11 12 20 14]]


3D- EXAMPLE

In [35]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
# get specific element ( work outside in )
b[0,1,1]

np.int64(4)

In [37]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [38]:
#replace
b[:,1,:]=[[9,9],[7,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [7 8]]]


Initializing Different Types of Arrays

In [43]:
# all 0s matriz
print(np.zeros(5))
print(np.zeros((2,3)))
print(np.zeros((2,3,3,2)))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]


In [44]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [46]:
# any other number
np.full((2,2),99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [47]:
# any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [49]:
# random decimal nos
np.random.rand(4,2,3)

array([[[0.44055734, 0.74381942, 0.98713536],
        [0.32529233, 0.4204698 , 0.25553005]],

       [[0.21985712, 0.04682801, 0.15652306],
        [0.09591889, 0.87744778, 0.07887376]],

       [[0.19101834, 0.35290287, 0.26373824],
        [0.42009316, 0.96699584, 0.26189993]],

       [[0.85623179, 0.97108486, 0.20247235],
        [0.82631544, 0.1680503 , 0.32044812]]])

In [50]:
np.random.random_sample(a.shape)

array([[0.9318488 , 0.02684144, 0.15150117, 0.34710381, 0.53792683,
        0.79767462, 0.81179224],
       [0.19699079, 0.05248303, 0.71834931, 0.22091663, 0.70610975,
        0.10713888, 0.71213672]])

In [51]:
#random integer values
np.random.randint(7)

1

In [52]:
np.random.randint(7,size=(3,3))

array([[3, 3, 2],
       [1, 1, 3],
       [3, 4, 6]])

In [55]:
np.random.randint(-4,7,size=(3,3))

array([[ 2,  3,  4],
       [ 0, -4, -2],
       [-3,  6, -2]])

In [56]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
#repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=1)
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [61]:
r2=np.repeat(arr,3,axis=0)
r2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

exercise: initialize the following matrix

1 1 1 1 1

1 0 0 0 1

1 0 9 0 1

1 0 9 0 1

1 0 0 0 1

1 1 1 1 1

In [67]:
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## be careful when copying elements

In [68]:
a=np.array([1,2,3])
b=a
b[0]=100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [70]:
b=a.copy()
b

array([100,   2,   3])

**Mathematics**

In [71]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [72]:
a+2

array([3, 4, 5, 6])

In [73]:
a-2

array([-1,  0,  1,  2])

In [74]:
a*2

array([2, 4, 6, 8])

In [75]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [76]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [77]:
a**2

array([ 1,  4,  9, 16])

In [78]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [79]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## LINEAR ALGEBRA

In [80]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [81]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [82]:
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

##Statistics

In [83]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
print(np.min(stats))
print(np.max(stats))

1
6


In [86]:
print(np.min(stats,axis=1)) # rows

[1 4]


In [87]:
print(np.min(stats,axis=0)) # cols

[1 2 3]


In [89]:
np.sum(stats, axis =0)

array([5, 7, 9])

##reorganizing arrays

In [95]:
before =np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

after=before.reshape((8,1))
print(after)

after2=before.reshape((2,2,2))
print(after2)

(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#Vertical stacking vectors

In [97]:
v1=np.array([1,2,3,4])
v2=np.array([4,5,6,7])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [98]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [1, 2, 3, 4],
       [4, 5, 6, 7]])

In [103]:
h1=np.ones((2,4))
h2=np.zeros((2,2))
print(h1)
print(h2)
np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#Miscellaneous

##load data from file

In [106]:
filedata=np.genfromtxt('/content/sample_data/data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [108]:
filedata=filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

  ## advanced indexing
  ## boolean masking

In [109]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [110]:
filedata[filedata>50]


array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [112]:
## you can index with a list in numpy
a= np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [113]:
np.any(filedata>50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [115]:
((filedata>50) & (filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [116]:
(~(filedata>50) & (filedata<100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

exercise

1 2 3 4 5

6 7 8 9 10

11 12 13 14 15

16 17 18 19 20

21 22 23 24 25

26 27 28 29 30

how to index 11, 12 , 16, 17?

ans: a[2:4,0:2]


how to index 2,8,14,20?

ans=a[[0,1,2,3],[1,2,3,4]]


how to index 4,5,24,25,29,30?

ans= a[[0,4,5],3:]